### ISSUE TITLE
Small tweak to the blog post

### ISSUE THREAD

**Issue by waldyrious** [denoland/roll-your-own-javascript-runtime#5]
I'd like to suggest a small adjustment to a passage in the [blog post](https://deno.com/blog/roll-your-own-javascript-runtime), to make it more readable and approachable:

Current:
> `deno_core` provides a `JsRuntime` struct that encapsulates V8 engine instance (so called `Isolate`)

Proposed:
> `deno_core` provides a `JsRuntime` struct that encapsulates a V8 engine instance (called an [`Isolate`](https://v8docs.nodesource.com/node-0.8/d5/dda/classv8_1_1_isolate.html#details))

Changes: added "a" before "V8 engine instance", replaced "so called `Isolate`" with "called an `Isolate`", and added a link to "Isolate".

An alternative link to the "Isolate" link could be from [this section of another blog post](https://deno.com/blog/anatomy-isolate-cloud#the-runner-as-an-isolate-hypervisor) (although it would be weird to have a blog post from July 2022 linking to a blog post from September 2022 :sweat_smile:), or [this section](https://choubey.gitbook.io/internals-of-deno/architecture/v8#isolate) from the "The Internals of Deno" book.

**Comment by bartlomieju** [comment]
Feel free to open a PR

EDIT: Err, sorry it seems you're mentioning private repo

**Comment by crowlKats** [comment]
This has been addressed

**Comment by waldyrious** [comment]
> Feel free to open a PR
>
> EDIT: Err, sorry it seems you're mentioning private repo

I suppose you keep the blog repo private to allow working on drafts without making them public, but how about making the blog repo public (so that it can receive PRs for issues like this one and #1), and maintaining a private fork of the repo for the drafts?

Edit: ah, I see, GitHub doesn't allow creating a private fork of a public repo. There are ways to work around this (e.g. making a private repo that's not marked as a fork, and simply adding this repo and the private fork as remotes in a local clone, so that they can be synced), but it I et that it could make things cumbersome for little benefit.
